version: '3'
services:
  dns:
    container_name: dns
    image: defreitas/dns-proxy-server
    hostname: dns
    domainname: internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf
    ports:
      - "5380:5380"
  icinga:
    container_name: icinga
    image: jordan/icinga2
    hostname: icinga
    domainname: internal
    ports:
      - "80:80"
  app1:
    container_name: app1
    image: carinamarina/hello-world-app
    hostname: app1
    domainname: internal
    ports:
      - "5000:5000"
  app2:
    container_name: app2
    image: carinamarina/hello-world-app
    hostname: app2
    domainname: internal
    ports:
      - "5001:5000"
  app3:
    container_name: app3
    image: carinamarina/hello-world-app
    hostname: app3
    domainname: internal
    ports:
      - "5002:5000"
