version: '3'
services:
  dns:
    container_name: dns
    image: defreitas/dns-proxy-server
    hostname: dns
    domainname: internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf
    ports:
      - "5380:5380"
  icinga:
    container_name: icinga
    image: jordan/icinga2
    hostname: icinga
    domainname: internal
    ports:
      - "80:80"
